baseurl = "https://blog.jace.pro/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Scripts and Snippets"
canonifyurls  = true
disablePathToLower = false

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "gggr"
#googleAnalytics = "XXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[Params]
  subtitle = "Notes to help me and some times you with your ServiceNow needs."
  # logo = "" # "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  # gcse = "007082590379751046943:au5jbfn4uby" 
  algolia = "0457ec3dd60c20e0dae38d0798c73506" # API key

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jace Benson"
#  gitlab = "jacebenson"
  github = "jacebenson"
  twitter = "jacebenson"
#  linkedin = "jacebenson"
#  stackoverflow = "users/546886/jace"
#  youtube = "user/jacebenson" # or channel/channelname


[[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    weight = 1000

# [[menu.main]]
#    parent = "blogs"
#     name = "Community Blogs"
#     url = "https://community.servicenow.com/community/blogs"
#     weight = 1010

[[menu.main]]
     parent = "blogs"
     name = "Travis Toulson's Blog"
     url = "https://codecreative.io/"
     weight = 1020

[[menu.main]]
     parent = "blogs"
     name = "Tim Woodruff's Blog"
     url = "https://snprotips.com/"
     weight = 1030

[[menu.main]]
      parent = "blogs"
      name = "Sal Costa's Blog"
      url = "http://snaug.com/"
     weight = 1040

[[menu.main]]
    parent = "blogs"
    name = "Mike Kaufman's Blog"
    url = "https://www.servicenowelite.com/blog"
    weight = 1060

[[menu.main]]
    parent = "blogs"
    name = "Ahmed Hmeid's Blog"
    url = "https://servicenowgems.com/"
    weight = 1070

[[menu.main]]
   parent = "blogs"
    name = "Shiva Thomas's Blog"
    url = "https://servicenow.implementation.blog/"
    weight = 1080

[[menu.main]]
    parent = "blogs"
    name = "Joel Maxwell's Blog"
    url = "http://sncommander.com/"
    weight = 1090

[[menu.main]]
    parent = "blogs"
    name = "Phuong's Blog"
    url = "https://helpfultechblog.com/"
    weight = 1100

[[menu.main]]
    identifier = "apis"
    name = "Server APIs"
    weight = 2000

# [[menu.main]]
#     parent = "apis"
#     name = "All"
#     url = "tags/server-side-api"
#     weight = 2005

[[menu.main]]
    parent = "apis"
    name = "Jelly"
    url = "jelly"
    weight = 2010

[[menu.main]]
    parent = "apis"
    name = "GlideAggregate"
    url = "glideaggregate"
    weight = 2050

[[menu.main]]
    parent = "apis"
    name = "GlideDateTime"
    url = "glidedatetime"
    weight = 2070

[[menu.main]]
    parent = "apis"
    name = "GlideEncrypter"
    url = "glideencrypter"
    weight = 2080

[[menu.main]]
    parent = "apis"
    name = "GlideFilter"
    url = "glidefilter"
    weight = 2090

[[menu.main]]
    parent = "apis"
    name = "GlideOAuth"
    url = "glideoauth"
    weight = 2100

[[menu.main]]
    parent = "apis"
    name = "GlideRecord"
    url = "gliderecord"
    weight = 2110

[[menu.main]]
    parent = "apis"
    name = "GlideSession"
    url = "glidesession"
    weight = 2120

[[menu.main]]
    parent = "apis"
    name = "GlideSystem aka gs"
    url = "gs"
    weight = 2130

[[menu.main]]
    parent = "apis"
    name = "GlideUser"
    url = "glideuser"
    weight = 2140

[[menu.main]]
    parent = "apis"
    name = "$SP"
    url = "sp"
    weight = 2200

[[menu.main]]
    parent = "apis"
    name = "Recordless Rest"
    url = "rest"
    weight = 2215

[[menu.main]]
    parent = "apis"
    name = "RestMessageV2"
    url = "restmessagev2"
    weight = 2220

[[menu.main]]
    parent = "apis"
    name = "RestResponseV2"
    url = "restresponsev2"
    weight = 2230

[[menu.main]]
    parent = "apis"
    name = "RestAPIRequest"
    url = "restapirequest"
    weight = 2240

[[menu.main]]
    parent = "apis"
    name = "RestAPIRequestBody"
    url = "restapirequestbody"
    weight = 2250

[[menu.main]]
    parent = "apis"
    name = "RestAPIResponse"
    url = "restapiresponse"
    weight = 2260

[[menu.main]]
    parent = "apis"
    name = "RestAPIResponseStream"
    url = "restapiresponsestream"
    weight = 2270

[[menu.main]]
    parent = "apis"
    name = "api/now/globalsearch"
    url = "api-now-globalsearch"
    weight = 2270

[[menu.main]]
    identifier = "apis-client"
    name = "Client APIs"
    weight = 2500

# [[menu.main]]
#     parent = "apis-client"
#     name = "All"
#     url = "tags/client-side-api"
#     weight = 2505

[[menu.main]]
    parent = "apis-client"
    name = "g_form"
    url = "g_form"
    weight = 2510

[[menu.main]]
    parent = "apis-client"
    name = "g_list"
    url = "g_list"
    weight = 2520

[[menu.main]]
    parent = "apis-client"
    name = "g_navigation"
    url = "g_navigation"
    weight = 2530

[[menu.main]]
    parent = "apis-client"
    name = "g_user"
    url = "g_user"
    weight = 2540

[[menu.main]]
    parent = "apis-client"
    name = "ScriptLoader"
    url = "scriptloader"
    weight = 2550

[[menu.main]]
    parent = "apis-client"
    name = "spUtil"
    url = "sputil"
    weight = 2560

[[menu.main]]
    parent = "apis-client"
    name = "GlideAjax"
    url = "glideajax"
    weight = 2060


[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 3000

[[menu.main]]
    parent = "resources"
    name = "Discord"
    url = "https://discord.gg/QaMwnGd"
    weight = 3010
    
[[menu.main]]
    parent = "resources"
    name = "StackOverflow"
    url = "https://stackoverflow.com/questions/tagged/servicenow"
    weight = 3020
    
[[menu.main]]
    parent = "resources"
    name = "r/servicenow"
    url = "https://reddit.com/r/servicenow"
    weight = 3030
    
[[menu.main]]
    parent = "resources"
    name = "Developer Meetups"
    url = "https://www.meetup.com/pro/servicenowdevprogram/"
    weight = 3040
    
[[menu.main]]
    parent = "resources"
    name = "Share"
    url = "https://developer.servicenow.com/app.do#!/share"
    weight = 3050

[[menu.main]]
    parent = "resources"
    name = "Platform Innovation Widgets"
    url = "https://sc.service-now.com/snds?state=featured-widgets&featured=true"
    weight = 3060

[[menu.main]]
    parent = "resources"
    name = "Attributes (Dictionary)"
    url = "attributes"
    weight = 2020

[[menu.main]]
    parent = "resources"
    name = "Attributes (Variable)"
    url = "attributes-vars"
    weight = 2030

[[menu.main]]
    parent = "resources"
    name = "Properties"
    url = "sys_properties"
    weight = 2040

[[menu.main]]
    parent = "resources"
    name = "K18 Lab Guides"
    url = "https://developer.servicenow.com/app.do#!/event/knowledge18"
    weight = 2050
    
[[menu.main]]
    parent = "resources"
    name = "K18 CreatorCon Lab Guides"
    url = "https://developer.servicenow.com/app.do#!/event/creatorcon18"
    weight = 2060
    
[[menu.main]]
    parent = "resources"
    name = "K19 Labs and CCWs"
    url = "https://developer.servicenow.com/app.do#!/event/knowledge19"
    weight = 2070

[[menu.main]]
    identifier = "docs"
    name = "Docs and Tools"
    weight = 4000

[[menu.main]]
    parent = "docs"
    name = "developer.servicenow.com"
    url = "https://developer.servicenow.com/app.do#!/api_doc"
    weight = 4010
    
[[menu.main]]
    parent = "docs"
    name = "docs.servicenow.com"
    url = "https://docs.servicenow.com/bundle/london-application-development/page/build/applications/concept/api-javascript.html"
    weight = 4020
    
[[menu.main]]
    parent = "docs"
    name = "Style Guide What"
    url = "http://styleguide.servicenow.com/"
    weight = 4030
    
[[menu.main]]
    parent = "docs"
    name = "Style Guide How"
    url = "https://hi.service-now.com/styles/heisenberg/styleguide/docs/index.html"
    weight = 4040
    
[[menu.main]]
    parent = "docs"
    name = "Retina Icons"
    url = "https://hi.service-now.com/styles/retina_icons/retina_icons.html"
    weight = 4050
    
[[menu.main]]
    parent = "docs"
    name = "Versions"
    url = "https://sndocs.jacebenson.com"
    weight = 4060
    
[[menu.main]]
    parent = "docs"
    name = "Workflow Diagrammer"
    url = "https://workflow.jacebenson.com"
    weight = 4070

[[menu.main]]
    parent = "docs"
    name = "Code Collab Tool"
    url = "https://code.jacebenson.com"
    weight = 4075
    
[[menu.main]]
    parent = "docs"
    name = "Bootstrap form builder"
    url = "http://bootsnipp.com/forms"
    weight = 4080

[[menu.main]]
    parent = "docs"
    name = "Angular 1.5.x"
    url = "https://code.angularjs.org/1.5.3/docs/api"
    weight = 4090

[[menu.main]]
    parent = "docs"
    name = "Bootstrap 3.3"
    url = "https://getbootstrap.com/docs/3.3/components/"
    weight = 4100

[[menu.main]]
    parent = "docs"
    name = "UI Bootstrap"
    url = "https://angular-ui.github.io/bootstrap/"
    weight = 4110

[[menu.main]]
    parent = "docs"
    name = "Formal Notices"
    url = "http://bureauofcommunication.com/"
    weight = 4120

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
